services:


  open-web-ui:
    image: ghcr.io/open-webui/open-webui:main
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DEFAULT_MODEL=gpt-4o-mini
      - ENABLE_OPENAI_API=true
      - OPENAI_API_BASE_URL=http://host.docker.internal:12000/v1

  jaeger:
    build:
      context: ../../shared/jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

  prometheus:
    build:
      context: ../../shared/prometheus

  grafana:
    build:
      context: ../../shared/grafana
    ports:
      - "3000:3000"
